language: android
sudo: false
jdk:
    - oraclejdk8

android:
    components:
        - build-tools-26.0.2
        - tools
        - platform-tools
        - tools
          # The SDK version used to compile your project
        - android-26

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-26

        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        - sys-img-armeabi-v7a-android-26
        - sys-img-armeabi-v7a-android-
env:
    global:
        - TERM=dumb
    matrix:
        - nodejs_version=8

install:
    - yes | sdkmanager tools > /dev/null
    - yes | sdkmanager --licenses > /dev/null

    - nvm install $nodejs_version    

    - npm install
    - npm install -g cordova
    - npm install -g mobileui

script:
    - gradle --version
    - node --version
    - npm --version
    - cordova platform add android
    - cordova build android

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Alexandre-Muzulao"
      - git config --local user.email "alexandre_muzulao@hotmail.com"
    #   - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      - git tag "v1.0.0"

deploy:
  provider: releases
  api_key: 
    secure: oX1q8nru+RIEOQ839VhgWYOQy7M2PDltntew953xX0D5y25cPq8x6eIPgxyqd9h9iTva0tOl/5OWVgkjzdp82LAKqU8qb87agtU28lOi5wsB5oHwUmis47SQyAGY8m1vhZjyTsmU/5uwqkb13V8WkAQxVPDdT7hzUISNkqD3SCtYPvdCpYyEvi/d/PxXA4cXRfLIg9KmO51Lwvm84O1erXmY1OXoFfcfej8wnA9Kd5KS/77T/N5s2dNDB8wk5qFCSut//fz8ixibaKQfZoqNiBtI366rPBzVqLblHxwWgTtSd2xCljqlBRDMqiNe5rgpJ+tGOicYyKQ3c+KrniiO2jJjTLa7NugrCMAv8rFO3Ftg3zQjq5XqW1v199eiZVj3q7+8saRk4Di/Yp5X81laTAWxndYEIhzd0a5T5YD0nqqTu1Vq8c3Jpg8cp/lGB93u7kcwS9lEEIh3xXzEdP+Yzp3u8IPVOeDsdKpYAMm2yjy6u55DOurW92QJXrUH8xeU+bZXs1Dp5nIx4ZXwZyAUlIA5KdQ2Tf2c8xmTzmKGmmWRfEB3WV+SJ6C62f3fAESr5ShYrScG8+gLaAAg4DcGT3uKex7BnYacswWjnoQG+dFlN7dvklZN7W4s+UEfUUWe8ZmvxWMy4ajJw5T6Pn17gU9kyVppvHqMUx3mWofZeY8=
  file: "/home/travis/build/Alexandre-Muzulao/BoraBeber/platforms/android/app/build/outputs/apk/debug/app-debug.apk"
  skip_cleanup: true
  on:
    repo: Alexandre-Muzulao/BoraBeber
    tags: true

after_script:
    - codecov